# Generated by Django 4.2.3 on 2023-07-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-is_done', '-created']},
        ),
    ]
